version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: payment_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: payment_system_app
    depends_on:
      - postgres
    ports:
      - "8181:8181"
    environment:
      SPRING_PROFILES_ACTIVE: local-docker
    command: ["java", "-jar", "/app/app.jar"]

volumes:
  postgres_data:
