spring:
  application:
    name: PaymentSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: 'classpath:db/db.changelog-master.yml'
    enabled: true
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock
    default-schema: 'payment'

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    root: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
